### ISSUE TITLE
Défaut d'affichage version mobile [Safari]

### ISSUE THREAD

**Issue by Lu7sodaa** [Skoli-Code/skoli-code.github.io#1]
- Padding démesuré entre le Titre et la baseline en cover 
- Accompagnela

**Comment by pbellon** [comment]
@Lu7sodaa on est sur le mauvais repository. Pour le padding il faudra m'expliquer plus en détail. Est-ce que tu peux faire ça [ici](https://github.com/Skoli-Code/website/issues/2) ?
